// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyn2W9EXMrXlE781ZsTvYGIxPLOpaddg',
    appId: '1:820256028416:web:914b68ce0436c8c3e2a5e5',
    messagingSenderId: '820256028416',
    projectId: 'psueducode-apk',
    authDomain: 'psueducode-apk.firebaseapp.com',
    databaseURL: 'https://psueducode-apk-default-rtdb.firebaseio.com',
    storageBucket: 'psueducode-apk.firebasestorage.app',
    measurementId: 'G-ELBJQ17M7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNqyr_61Ir4zpImcFNERctFtdndyo53k',
    appId: '1:820256028416:android:2b65bf01d4d42ef9e2a5e5',
    messagingSenderId: '820256028416',
    projectId: 'psueducode-apk',
    databaseURL: 'https://psueducode-apk-default-rtdb.firebaseio.com',
    storageBucket: 'psueducode-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yiHcXnaTydRxrSXejeCDIWqewhtERHU',
    appId: '1:820256028416:ios:c7f34463178f0caee2a5e5',
    messagingSenderId: '820256028416',
    projectId: 'psueducode-apk',
    databaseURL: 'https://psueducode-apk-default-rtdb.firebaseio.com',
    storageBucket: 'psueducode-apk.firebasestorage.app',
    iosBundleId: 'com.example.pseudocodeApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7yiHcXnaTydRxrSXejeCDIWqewhtERHU',
    appId: '1:820256028416:ios:c7f34463178f0caee2a5e5',
    messagingSenderId: '820256028416',
    projectId: 'psueducode-apk',
    databaseURL: 'https://psueducode-apk-default-rtdb.firebaseio.com',
    storageBucket: 'psueducode-apk.firebasestorage.app',
    iosBundleId: 'com.example.pseudocodeApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmyn2W9EXMrXlE781ZsTvYGIxPLOpaddg',
    appId: '1:820256028416:web:8f240ade59805124e2a5e5',
    messagingSenderId: '820256028416',
    projectId: 'psueducode-apk',
    authDomain: 'psueducode-apk.firebaseapp.com',
    databaseURL: 'https://psueducode-apk-default-rtdb.firebaseio.com',
    storageBucket: 'psueducode-apk.firebasestorage.app',
    measurementId: 'G-SMJC24GCYZ',
  );
}
